function printTestResults(results)
%PRINTTESTRESULTS Prints all the test results.
%   Detailed explanation goes here
    statuses = {results.status};

    fprintf('\nCellModel test summary: %d passed, %d skipped, %d failed\n', ...
        sum(strcmp(statuses, 'passed')), ...
        sum(strcmp(statuses, 'skipped')), ...
        sum(strcmp(statuses, 'failed')));
    
    for index = 1:numel(results)
        fprintf('[%s] %s: %s\n', ...
            upper(results(index).status), ...
            results(index).name, ...
            results(index).message);
    end
end